In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('..\\..\\..\\data\\0_data\\survey_results_public.csv', index_col = 'Respondent')
schema_df = pd.read_csv('..\\..\\..\\data\\0_data\survey_results_schema.csv', index_col = 'Column')

In [3]:
df.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [9]:
df['YearsCode'].value_counts()

5                     7047
10                    6777
6                     6179
4                     5729
8                     5361
7                     5320
3                     5179
2                     3974
15                    3942
20                    3636
12                    3530
9                     3360
11                    2265
14                    2126
13                    2036
18                    1900
1                     1814
25                    1657
16                    1593
30                    1532
Less than 1 year      1367
17                    1349
19                    1018
22                    1016
35                     873
23                     745
21                     715
24                     693
40                     497
28                     465
32                     420
26                     409
27                     408
33                     353
38                     340
34                     327
37                     321
36                     308
29                     234
31                     202
39                     170
More than 50 years     126
42                     115
45                     113
41                      92
43                      83
44                      52
50                      51
47                      36
48                      31
46                      27
49                      25
Name: YearsCode, dtype: int64

In [11]:
df['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 'Less than 1 year', '30', '9', '26', '40', '19',
       '15', '20', '28', '25', '1', '22', '11', '33', '50', '41', '18',
       '34', '24', '23', '42', '27', '21', '36', '32', '39', '38', '31',
       '37', 'More than 50 years', '29', '44', '45', '48', '46', '43',
       '47', '49'], dtype=object)

In [4]:
# df['YearsCode'].replace('Less than 1 year',1,inplace=True)
# df['YearsCode'].replace('More than 50 years',50,inplace=True)
# df['YearsCode'].astype(float).mean()

In [14]:
df.to_csv('..\\..\\..\\data\\0_data\\copy1.csv')